version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: backend_chat_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_forte
      POSTGRES_DB: backend_chat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
